### ISSUE TITLE
Use idiomatic style for Go comments.

### ISSUE THREAD

**Issue by dmitshur** [go-gl/cl#1]
Hi,

I see this package has a lot of comments without a space after the two forward slashes, e.g.:

``` Go
//Create Command Queue
```

Idiomatic Go style for comments is to include a space after the two forward slashes, so it should be:

``` Go
// Create Command Queue
```

See https://golang.org/doc/effective_go.html#commentary and https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences.

No space is used for commented out code and non-compiler directives, for example:

```
//go:generate foo
```

**Comment by dmitshur** [comment]
Also, @hydroflame, you were asking for suggestions of better style to use for section separator comments. I think I've found an example of such separator comments in the Go standard library. I suggest you copy that style rather than coming up with your own.

See http://gotools.org/go/token.

``` Go
// IsValid returns true if the position is valid.
func (p Pos) IsValid() bool {
    return p != NoPos
}

// -----------------------------------------------------------------------------
// File

// A File is a handle for a file belonging to a FileSet.
// A File has a name, size, and line offset table.
//
type File struct {
    set  *FileSet
```

Note that `// -----------------------------------------------------------------------------` is exactly 80 characters long.

I hope you find this suggestion useful.

**Comment by ghost** [comment]
hey @shurcooL can you verify that comments on master are idiomatic ?

**Comment by ghost** [comment]
> everything looks perfect, except https://github.com/go-gl/cl/commit/e3c67203f05576361da4ec9d5a32939cb6f02c9e#commitcomment-12916230
> -shurcooL

i fixed that so im closing now
