### ISSUE TITLE
Pointer to pointer values as cgo arguments are no longer allowed in Go 1.6

### ISSUE THREAD

**Issue by 1lann** [go-gl/cl#2]
Any calls to functions which calls cgo with a double pointer, (for example CreateProgramWithSource) will cause a runtime error:
`panic: runtime error: cgo argument has Go pointer to Go pointer`
In Go 1.6 as a result of the changes to cgo: https://tip.golang.org/doc/go1.6#cgo

I noticed you guys are already aware of this for OpenGL bindings: https://github.com/go-gl/gl/issues/31

**Comment by EtienneBruines** [comment]
This is probably a matter of regenerating the bindings (since it's already been fixed on similar repos). 

@hydroflame I'm not sure if this is something you're still able to do?

**Comment by ghost** [comment]
Added utility function like the rest of the go-gl packages, is that good ?

**Comment by 1lann** [comment]
Seems to be fixed a long while ago, I'm guessing it's safe to close this now.
